name: Test and release
on:
    push:

jobs:
    release:
        runs-on: ubuntu-20.04
        if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create docker tags
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: ghcr.io/riotkit-org/libre-etherpad

            - name: Build and release docker
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
